---
title: "Adaptations"
output: html_document
author: "Daniella Maor"
---

```{r packages}
options(repos = c(CRAN = "https://cloud.r-project.org"))
install.packages("gghighlight")

library(magrittr)
library(dplyr)
library(lubridate)
library(ggplot2)
library(tidyverse)
library(gghighlight)
```


```{r data-load}
spl_data <- read.csv(file = "https://seattle-library-checkout-data.s3.us-west-2.amazonaws.com/norton-anthology_spl-checkouts_2005-2025.csv", header = TRUE, stringsAsFactors = FALSE)

adaptation_authors <- c("Chris Kraus", "Don DeLillo", "Philip Roth", "Philip K. Dick", "Viet Thanh Nguyen", "Octavia E. Butler", "james baldwin", "thomas pynchon")
```


```{r get-authors}
adaptation_df <- spl_data %>%
  filter(grepl(paste(adaptation_authors, collapse = "|"), Normalized.Creator, ignore.case = TRUE))
```


```{r date-fix}
adaptation_df %<>%
  mutate(CheckoutDate = as.Date(paste(CheckoutYear, CheckoutMonth, "01", sep = "-")))
```

```{r titles}
titles <- c("White Noise", "Do Androids Dream Of Electric Sheep", "American Pastoral", "The Sympathizer", "Kindred", "A Scanner Darkly", "The Man In The High Castle", "If Beale Street Could Talk", "Inherent Vice")
```


```{r set-movie-tv-dates}
tv_titles <- c("The Man In The High Castle", "Kindred", "The Sympathizer")

movie_titles <- c("White Noise", "Do Androids Dream Of Electric Sheep", "American Pastoral", "A Scanner Darkly", "If Beale Street Could Talk", "Inherent Vice")

movie_info <- data.frame(
  Normalized.Title = movie_titles,
  ReleaseDate = as.Date(c("2022-08-31", "2017-10-06", "2016-10-13", "2006-07-07", "2018-12-25", "2014-12-12"))
)

tv_info <- data.frame(
  Normalized.Title = tv_titles,
  FirstEpisode = as.Date(c("2015-01-15", "2022-12-13", "2024-04-14")),
  LastEpisode = as.Date(c("2019-11-15", "2023-01-13", "2024-05-26"))
)
```

```{r merge-data}
movie_data <- left_join(adaptation_df, movie_info, by = "Normalized.Title")
tv_data <- left_join(adaptation_df, tv_info, by = "Normalized.Title")
```

# TV Show Adaptation Plot

```{r tv-plot}
tv_data %>%
  filter(Normalized.Title %in% tv_titles) %>%
  group_by(Normalized.Title, CheckoutDate, FirstEpisode, LastEpisode) %>%
  summarize(Checkouts = sum(Checkouts)) %>%
  ggplot(aes(x = CheckoutDate, y = Checkouts)) +
  geom_line(size = 0.75) +
  facet_wrap(~Normalized.Title, scales = "free_x") +
  labs(
    x = "Checkout Date",
    y = "Number of Checkouts",
    title = "Number of SPL Check Outs for Works with TV Show Adaptations",
    subtitle = "For Authors in the Norton Anthology"
  ) +
  geom_vline(aes(xintercept = FirstEpisode), linetype = "dashed", color = "skyblue") +
  geom_vline(aes(xintercept = LastEpisode), linetype = "dashed", color = "skyblue") +
  geom_rect(aes(xmin = FirstEpisode, xmax = LastEpisode, ymin = -Inf, ymax = Inf),
    fill = "skyblue", alpha = 0.006
  ) +
  theme_light()
```

# Movie Adaptation Plot

```{r movie-plot}
movie_data %>%
  filter(Normalized.Title %in% movie_titles) %>%
  group_by(Normalized.Title, CheckoutDate, ReleaseDate, Normalized.Creator) %>%
  summarize(Checkouts = sum(Checkouts)) %>%
  ggplot(aes(x = CheckoutDate, y = Checkouts)) +
  geom_line(size = 0.75) +
  facet_wrap(~Normalized.Title, scales = "free_y", nrow = 3, ncol = 2) +
  labs(
    x = "Checkout Date",
    y = "Number of Checkouts",
    title = "Number of SPL Check Outs for Works with Movie Adaptations",
    subtitle = "For Authors in the Norton Anthology"
  ) +
  geom_vline(aes(xintercept = ReleaseDate), linetype = "dashed", color = "hotpink", size = 0.75) +
  theme_light()
```






# Individual Plots

```{r sympathizer}
adaptation_df %>%
  filter(Normalized.Title == "The Sympathizer") %>%
  group_by(Normalized.Title, CheckoutDate, Normalized.Creator) %>%
  summarize(Checkouts = sum(Checkouts)) %>%
  ggplot(aes(x = CheckoutDate, y = Checkouts)) +
  geom_line(size = 0.75) +
  labs(
    x = "Checkout Date",
    y = "Number of Checkouts",
    title = "Number of Check Outs for The Sympathizer"
  ) +
  geom_vline(xintercept = as.Date("2024-04-14"), linetype = "dashed", color = "red") +
  geom_vline(xintercept = as.Date("2024-05-26"), linetype = "dashed", color = "red") +
  annotate("rect", xmin = as.Date("2024-04-14"), xmax = as.Date("2024-05-26"), fill = "#ff8f8f", ymin = -Inf, ymax = Inf, alpha = 0.5) +
  theme_light()
```

```{r i-love-dick}
adaptation_df %>%
  filter(Normalized.Title == "I Love Dick") %>%
  group_by(Normalized.Title, CheckoutDate, Normalized.Creator) %>%
  summarize(Checkouts = sum(Checkouts)) %>%
  ggplot(aes(x = CheckoutDate, y = Checkouts)) +
  geom_line(size = 0.75, color = "black") +
  labs(
    x = "Checkout Date",
    y = "Number of Checkouts",
    title = "Number of Check Outs for I Love Dick"
  ) +
  geom_vline(xintercept = as.Date("2016-08-19"), linetype = "dashed", color = "hotpink") +
  geom_vline(xintercept = as.Date("2017-05-12"), linetype = "dashed", color = "hotpink") +
  annotate("rect", xmin = as.Date("2016-08-19"), xmax = as.Date("2017-05-12"), fill = "pink", ymin = -Inf, ymax = Inf, alpha = 0.5) +
  theme_light()
```

```{r whitenoise}
adaptation_df %>%
  filter(Normalized.Title == "White Noise") %>%
  group_by(Normalized.Title, CheckoutDate, Normalized.Creator) %>%
  summarize(Checkouts = sum(Checkouts)) %>%
  ggplot(aes(x = CheckoutDate, y = Checkouts)) +
  geom_line(size = 0.75) +
  labs(
    x = "Checkout Date",
    y = "Number of Checkouts",
    title = "Number of Check Outs for White Noise"
  ) +
  geom_vline(xintercept = as.Date("2022-08-31"), linetype = "dashed", color = "red") +
  theme_light()
```

```{r blade-runner}
adaptation_df %>%
  filter(Normalized.Title == "Do Androids Dream Of Electric Sheep") %>%
  group_by(Normalized.Title, CheckoutDate, Normalized.Creator) %>%
  summarize(Checkouts = sum(Checkouts)) %>%
  ggplot(aes(x = CheckoutDate, y = Checkouts)) +
  geom_line(size = 0.75) +
  labs(
    x = "Checkout Date",
    y = "Number of Checkouts",
    title = "Number of Check Outs for Do Androids Dream Of Electric Sheep"
  ) +
  geom_vline(xintercept = as.Date("2017-10-06"), linetype = "dashed", color = "orange") +
  theme_light()
```


```{r}
adaptation_df %>%
  filter(Normalized.Title == "American Pastoral") %>%
  group_by(Normalized.Title, CheckoutDate, Normalized.Creator) %>%
  summarize(Checkouts = sum(Checkouts)) %>%
  ggplot(aes(x = CheckoutDate, y = Checkouts)) +
  geom_line(size = 0.75) +
  labs(
    x = "Checkout Date",
    y = "Number of Checkouts",
    title = "Number of Check Outs for American Pastoral"
  ) +
  geom_vline(xintercept = as.Date("2016-10-13"), linetype = "dashed", color = "blue") +
  theme_light()
```


```{r Kindred}
adaptation_df %>%
  filter(Normalized.Title == "Kindred") %>%
  group_by(Normalized.Title, CheckoutDate, Normalized.Creator) %>%
  summarize(Checkouts = sum(Checkouts)) %>%
  ggplot(aes(x = CheckoutDate, y = Checkouts)) +
  geom_line(size = 0.75, color = "black") +
  labs(
    x = "Checkout Date",
    y = "Number of Checkouts",
    title = "Number of Check Outs for Kindred"
  ) +
  geom_vline(xintercept = as.Date("2022-12-13"), linetype = "dashed", color = "green") +
  geom_vline(xintercept = as.Date("2023-01-13"), linetype = "dashed", color = "green") +
  annotate("rect", xmin = as.Date("2022-12-13"), xmax = as.Date("2023-01-13"), fill = "green", ymin = -Inf, ymax = Inf, alpha = 0.3) +
  theme_light()
```

```{r Scanner-Darkly}
adaptation_df %>%
  filter(Normalized.Title == "A Scanner Darkly") %>%
  group_by(Normalized.Title, CheckoutDate, Normalized.Creator) %>%
  summarize(Checkouts = sum(Checkouts)) %>%
  ggplot(aes(x = CheckoutDate, y = Checkouts)) +
  geom_line(size = 0.75, color = "black") +
  labs(
    x = "Checkout Date",
    y = "Number of Checkouts",
    title = "Number of Check Outs for A Scanner Darkly"
  ) +
  geom_vline(xintercept = as.Date("2006-07-07"), linetype = "dashed", color = "purple") +
  theme_light()
```


```{r high-castle}
adaptation_df %>%
  filter(Normalized.Title == "The Man In The High Castle") %>%
  group_by(Normalized.Title, CheckoutDate, Normalized.Creator) %>%
  summarize(Checkouts = sum(Checkouts)) %>%
  ggplot(aes(x = CheckoutDate, y = Checkouts)) +
  geom_line(size = 0.75, color = "black") +
  labs(
    x = "Checkout Date",
    y = "Number of Checkouts",
    title = "Number of Check Outs for Man In The High Castle"
  ) +
  geom_vline(xintercept = as.Date("2015-01-15"), linetype = "dashed", color = "orange") +
  geom_vline(xintercept = as.Date("2019-11-15"), linetype = "dashed", color = "orange") +
  annotate("rect", xmin = as.Date("2015-01-15"), xmax = as.Date("2019-11-15"), fill = "orange", ymin = -Inf, ymax = Inf, alpha = 0.3) +
  theme_light()
```

```{r Beale-Street}
adaptation_df %>%
  filter(Normalized.Title == "If Beale Street Could Talk") %>%
  group_by(Normalized.Title, CheckoutDate, Normalized.Creator) %>%
  summarize(Checkouts = sum(Checkouts)) %>%
  ggplot(aes(x = CheckoutDate, y = Checkouts)) +
  geom_line(size = 0.75, color = "black") +
  labs(
    x = "Checkout Date",
    y = "Number of Checkouts",
    title = "Number of Check Outs for If Beale Street Could Talk"
  ) +
  geom_vline(xintercept = as.Date("2018-12-25"), linetype = "dashed", color = "magenta") +
  theme_light()
```


```{r Inherent-Vice}
adaptation_df %>%
  filter(Normalized.Title == "Inherent Vice") %>%
  group_by(Normalized.Title, CheckoutDate, Normalized.Creator) %>%
  summarize(Checkouts = sum(Checkouts)) %>%
  ggplot(aes(x = CheckoutDate, y = Checkouts)) +
  geom_line(size = 0.75, color = "black") +
  labs(
    x = "Checkout Date",
    y = "Number of Checkouts",
    title = "Number of Check Outs for Inherent Vice"
  ) +
  geom_vline(xintercept = as.Date("2014-12-12"), linetype = "dashed", color = "magenta") +
  theme_light()
```

